//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppsOppgave1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bookings
    {
        public int Id { get; set; }
        public int Amount { get; set; }
        public Nullable<int> Flight_Id { get; set; }
        public Nullable<int> User_Id { get; set; }
    
        public virtual Flights Flights { get; set; }
        public virtual Users Users { get; set; }
    }
}
