//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppsOppgave1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flights
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Flights()
        {
            this.Airports = new HashSet<Airports>();
        }
    
        public int Id { get; set; }
        public System.DateTime Departure { get; set; }
        public Nullable<int> FromAirport_Id { get; set; }
        public Nullable<int> ToAirport_Id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Airports> Airports { get; set; }
        public virtual Airports Airports1 { get; set; }
        public virtual Airports Airports2 { get; set; }
        public virtual Bookings Bookings { get; set; }
    }
}
